/**
 * Crossword provider
 * Access to crosswords puzzle generator
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CellQuestions_allOf.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

CellQuestions_allOf::CellQuestions_allOf(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string CellQuestions_allOf::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void CellQuestions_allOf::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree CellQuestions_allOf::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	// generate tree for Questions
    tmp_node.clear();
	if (!m_Questions.empty()) {
        tmp_node = toPt(m_Questions);
		pt.add_child("questions", tmp_node);
		tmp_node.clear();
	}
	return pt;
}

void CellQuestions_allOf::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	// push all items of Questions into member
	if (pt.get_child_optional("questions")) {
        m_Questions = fromPt<std::vector<Question>>(pt.get_child("questions"));
	}
}

std::vector<Question> CellQuestions_allOf::getQuestions() const
{
    return m_Questions;
}

void CellQuestions_allOf::setQuestions(std::vector<Question> value)
{
    m_Questions = value;
}



std::vector<CellQuestions_allOf> createCellQuestions_allOfVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<CellQuestions_allOf>();
    for (const auto& child: pt) {
        vec.emplace_back(CellQuestions_allOf(child.second));
    }

    return vec;
}

}
}
}
}

