/**
 * Crossword provider
 * Access to crosswords puzzle generator
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CellLetter.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

CellLetter::CellLetter(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string CellLetter::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void CellLetter::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree CellLetter::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	pt.put("color", m_Color);
	pt.put("letter", m_Letter);
	pt.put("solutionWordIndex", m_SolutionWordIndex);
	return pt;
}

void CellLetter::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_Color = pt.get("color", "");
	m_Letter = pt.get("letter", "");
	m_SolutionWordIndex = pt.get("solutionWordIndex", 0);
}

std::string CellLetter::getColor() const
{
    return m_Color;
}

void CellLetter::setColor(std::string value)
{
    m_Color = value;
}


std::string CellLetter::getLetter() const
{
    return m_Letter;
}

void CellLetter::setLetter(std::string value)
{
    m_Letter = value;
}


int32_t CellLetter::getSolutionWordIndex() const
{
    return m_SolutionWordIndex;
}

void CellLetter::setSolutionWordIndex(int32_t value)
{
    m_SolutionWordIndex = value;
}



std::vector<CellLetter> createCellLetterVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<CellLetter>();
    for (const auto& child: pt) {
        vec.emplace_back(CellLetter(child.second));
    }

    return vec;
}

}
}
}
}

