/**
 * Crossword provider
 * Access to crosswords puzzle generator
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "Crossword_content_inner_inner.h"

#include <string>
#include <vector>
#include <map>
#include <sstream>
#include <stdexcept>
#include <regex>
#include <boost/lexical_cast.hpp>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/json_parser.hpp>
#include "helpers.h"

using boost::property_tree::ptree;
using boost::property_tree::read_json;
using boost::property_tree::write_json;

namespace org {
namespace openapitools {
namespace server {
namespace model {

Crossword_content_inner_inner::Crossword_content_inner_inner(boost::property_tree::ptree const& pt)
{
        fromPropertyTree(pt);
}


std::string Crossword_content_inner_inner::toJsonString(bool prettyJson /* = false */) const
{
	std::stringstream ss;
	write_json(ss, this->toPropertyTree(), prettyJson);
    // workaround inspired by: https://stackoverflow.com/a/56395440
    std::regex reg("\\\"([0-9]+\\.{0,1}[0-9]*)\\\"");
    std::string result = std::regex_replace(ss.str(), reg, "$1");
    return result;
}

void Crossword_content_inner_inner::fromJsonString(std::string const& jsonString)
{
	std::stringstream ss(jsonString);
	ptree pt;
	read_json(ss,pt);
	this->fromPropertyTree(pt);
}

ptree Crossword_content_inner_inner::toPropertyTree() const
{
	ptree pt;
	ptree tmp_node;
	pt.put("color", m_Color);
	pt.put("letter", m_Letter);
	pt.put("solutionWordIndex", m_SolutionWordIndex);
	// generate tree for Questions
    tmp_node.clear();
	if (!m_Questions.empty()) {
        tmp_node = toPt(m_Questions);
		pt.add_child("questions", tmp_node);
		tmp_node.clear();
	}
	return pt;
}

void Crossword_content_inner_inner::fromPropertyTree(ptree const &pt)
{
	ptree tmp_node;
	m_Color = pt.get("color", "");
	m_Letter = pt.get("letter", "");
	m_SolutionWordIndex = pt.get("solutionWordIndex", 0);
	// push all items of Questions into member
	if (pt.get_child_optional("questions")) {
        m_Questions = fromPt<std::vector<Question>>(pt.get_child("questions"));
	}
}

std::string Crossword_content_inner_inner::getColor() const
{
    return m_Color;
}

void Crossword_content_inner_inner::setColor(std::string value)
{
    m_Color = value;
}


std::string Crossword_content_inner_inner::getLetter() const
{
    return m_Letter;
}

void Crossword_content_inner_inner::setLetter(std::string value)
{
    m_Letter = value;
}


int32_t Crossword_content_inner_inner::getSolutionWordIndex() const
{
    return m_SolutionWordIndex;
}

void Crossword_content_inner_inner::setSolutionWordIndex(int32_t value)
{
    m_SolutionWordIndex = value;
}


std::vector<Question> Crossword_content_inner_inner::getQuestions() const
{
    return m_Questions;
}

void Crossword_content_inner_inner::setQuestions(std::vector<Question> value)
{
    m_Questions = value;
}



std::vector<Crossword_content_inner_inner> createCrossword_content_inner_innerVectorFromJsonString(const std::string& json)
{
    std::stringstream sstream(json);
    boost::property_tree::ptree pt;
    boost::property_tree::json_parser::read_json(sstream,pt);

    auto vec = std::vector<Crossword_content_inner_inner>();
    for (const auto& child: pt) {
        vec.emplace_back(Crossword_content_inner_inner(child.second));
    }

    return vec;
}

}
}
}
}

